Aula 02 - Python



In [1]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)


Valor de a = 1


int

In [3]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)


1.0


float

In [4]:
# Converter float para int
c = int(b)
print(c)
type(c)


1


int

In [9]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)




nan


float

In [10]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)


nan
nan
1.0


In [11]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)


Fábio
Gabriel
FábioGabriel
Fábio Gabriel


In [12]:
a == 1


True

In [13]:
h = (a==1)
print(h)
type(h)


True


bool

In [14]:
h = (a==2)
print(h)
type(h)


False


bool

In [15]:
i = True
type(i)


bool

In [16]:
ii = 'True'
type(ii)


str

In [17]:
# Operação ==
a==b


True

In [18]:
# Operação ><
a>b


False

In [19]:
# Operação !=
a!=b


False

In [20]:
# Operação >= ou <=
a>=b


True

In [21]:
# Soma 
a+b

2.0

In [22]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [23]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [24]:
# Divisão
a/b

1.0

In [25]:
# Potencia
5**2

25

In [26]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [27]:
math.exp(0)


1.0

In [28]:
math.exp(a)


2.718281828459045

In [29]:
math.exp(-10)

4.5399929762484854e-05

In [34]:
import math as mt

# Calculando o logaritmo de c
resultado = mt.log(c)

# Imprimindo o resultado
print(resultado)  # Saída: valor do logaritmo de c



0.0


In [35]:
mt.log10(100)


2.0

In [36]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [37]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [38]:
myFirstList==a


False

In [39]:
myFirstList[0]==a

True

In [40]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [41]:
type(mySecList)

list

In [43]:
type(mySecList[2])


str

In [44]:
type(mySecList[1])


int

In [47]:
path = r"C:\Users\D:\ENS5173_01"
print(path)
print(path)

C:\Users\D:\ENS5173_01
C:\Users\D:\ENS5173_01


In [49]:
path = "C:/Users/D:/ENS5173_01"
print(path)


C:/Users/D:/ENS5173_01


In [51]:
import os

# Caminho correto para o diretório
path = "D:/ENS5173_01"

# Listar arquivos na pasta
files = os.listdir(path)
print(files)


['.git', '.gitignore', '.ipynb_checkpoints', 'aula02.ipynb', 'pyEnv', 'README.md', 'scripts']


In [52]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [53]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'D:/ENS5173_01/.git'

In [54]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [55]:
# Diretório que estou trababalhando
os.getcwd()

'D:\\ENS5173_01'

In [58]:
# Mudo de diretório para o caminho 
import os

# Mudar para o diretório ENS5173_01 na unidade D
os.chdir('D:\\ENS5173_01')

# Listar os arquivos no diretório
files = os.listdir()
print(files)

['.git', '.gitignore', '.ipynb_checkpoints', 'aula02.ipynb', 'pyEnv', 'README.md', 'scripts']


In [59]:
os.getcwd()

'D:\\ENS5173_01'

In [60]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório D:\ENS5173_01/test


In [61]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório D:\ENS5173_01/test2


In [62]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [63]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [64]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.15582336 0.78005882 0.99951128 0.96610812 0.2755383  0.91943812
  0.41509669 0.19574604 0.71400563 0.32259743]
 [0.46680596 0.83872091 0.8709472  0.67823728 0.86742611 0.22204245
  0.62333162 0.66692096 0.24572191 0.94691771]
 [0.61672926 0.40861601 0.79205853 0.11876821 0.11220589 0.82185513
  0.09475671 0.27223085 0.8519566  0.52748354]
 [0.38718133 0.99210273 0.44082494 0.96104229 0.0043616  0.72450547
  0.81457309 0.30905639 0.92294183 0.09197877]
 [0.83701986 0.38245554 0.79543565 0.61988944 0.36902601 0.80205179
  0.36082652 0.08769747 0.07356677 0.02668737]
 [0.30910107 0.90991378 0.11142082 0.47670123 0.38244644 0.863977
  0.23892681 0.57373077 0.0960018  0.211908  ]
 [0.60764389 0.43396927 0.23488653 0.05019413 0.56291431 0.64995828
  0.34149213 0.62331247 0.0150329  0.35513132]
 [0.15593096 0.90341379 0.27312723 0.16385966 0.05169888 0.94568908
  0.80169729 0.81037819 0.86669402 0.10827726]
 [0.64887161 0.05310248 0.53666512 0.52152093 0.4104387  0.29525444
  0.21229694 0

In [65]:
# Acessando valores da matriz
n[0,:]

array([0.15582336, 0.78005882, 0.99951128, 0.96610812, 0.2755383 ,
       0.91943812, 0.41509669, 0.19574604, 0.71400563, 0.32259743])

In [66]:
n[:,0]

array([0.15582336, 0.46680596, 0.61672926, 0.38718133, 0.83701986,
       0.30910107, 0.60764389, 0.15593096, 0.64887161, 0.9658955 ])

In [67]:
n[:,1:5]

array([[0.78005882, 0.99951128, 0.96610812, 0.2755383 ],
       [0.83872091, 0.8709472 , 0.67823728, 0.86742611],
       [0.40861601, 0.79205853, 0.11876821, 0.11220589],
       [0.99210273, 0.44082494, 0.96104229, 0.0043616 ],
       [0.38245554, 0.79543565, 0.61988944, 0.36902601],
       [0.90991378, 0.11142082, 0.47670123, 0.38244644],
       [0.43396927, 0.23488653, 0.05019413, 0.56291431],
       [0.90341379, 0.27312723, 0.16385966, 0.05169888],
       [0.05310248, 0.53666512, 0.52152093, 0.4104387 ],
       [0.61202399, 0.85240705, 0.46873533, 0.12778422]])

In [68]:
n[0,1:5]

array([0.78005882, 0.99951128, 0.96610812, 0.2755383 ])

In [69]:
n[0,-1]

0.3225974276936975

In [70]:
n[0,4:]

array([0.2755383 , 0.91943812, 0.41509669, 0.19574604, 0.71400563,
       0.32259743])

In [71]:
an = np.log(n*5)
print(an)

[[-0.24959429  1.36105195  1.60894908  1.57495838  0.32040926  1.52544538
   0.73019412 -0.02149928  1.27257349  0.47808783]
 [ 0.84759631  1.43356063  1.47126398  1.22117983  1.46721296  0.10455119
   1.13676131  1.20435417  0.20588309  1.55489483]
 [ 1.12611276  0.71445849  1.37631793 -0.52114361 -0.57798184  1.41324677
  -0.74700476  0.30833306  1.44921822  0.9698003 ]
 [ 0.66057577  1.6015093   0.79033048  1.56970104 -3.82547785  1.28717195
   1.40434679  0.43520637  1.52924885 -0.77675956]
 [ 1.43153043  0.64829506  1.38057259  1.13122378  0.61254976  1.38885581
   0.59007991 -0.8244243  -1.00012399 -2.01412697]
 [ 0.43535095  1.51503248 -0.58500312  0.86857258  0.64827124  1.46322878
   0.17783989  1.05384288 -0.73395041  0.05783483]
 [ 1.11127164  0.77465637  0.16078518 -1.3824192   1.03481005  1.17859081
   0.53500726  1.13673058 -2.58807624  0.57417027]
 [-0.24890404  1.50786332  0.31162038 -0.19930703 -1.35288124  1.55359648
   1.38841372  1.39918367  1.46636863 -0.6136222 ]
